### PR TITLE
Add underscores to constraints + let interpreters define their own monads

### PR DESCRIPTION
**Pull request by crossroads1112**

### CODE REVIEW

**Comment by cpeikert** [comment]
We didn't discuss whether associated constraints should get the underscore. Part of me says "no" because the constraints live entirely on (the LHS of) Haskell terms, and never appear in object-language types. The other part of me says "yes" because they are part of DSL components, and we don't want conflicts with similarly named constraints from, e.g., Lol's SHE. (Though I guess we didn't have such conflicts.)

Am I missing a compelling argument one way or the other? (The winning argument may be that you already did it...)

**Comment by crossroads1112** [comment]
Ooh yeah, good thought. I thought the associated constraints were included in our discussion of associated types, but I still struggled with this when I was making the change. 

I agree that these are fundamentally different from the associated types , but one could make the same argument, that e.g. `Mul_` only ever appears on the LHS of Haskell terms as well. I think avoiding the name conflict with SHE is somewhat telling too. `ModSwitchCtx_` is the DSL version of `ModSwitchCtx`.

I didn't add underscores to e.g. `KeysAccumulatorCtx` or `PT2CTMulCtx` though since these are tied to the metalanguage and a specific interpreter respectively.

**Comment by crossroads1112** [comment]
That said, I am very sympathetic to the "no" argument as well, so I am happy to change them all back.

**Comment by cpeikert** [comment]
We easily avoided the name conflict in SHE by importing Lol's SHE qualified, and users of Alchemy's SHE shouldn't ever have to touch Lol's SHE (or we haven't done our job!).

It's a fair point that things like `Mul_` end up in the LHS of signatures. If we consider the full type of some DSL term, it's going to have constraints like `Mul_` and some `Ctx`-style constraints. I guess it is better that all of these end in underscores to indicate where they came from.

**Comment by crossroads1112** [comment]
> users of Alchemy's SHE shouldn't ever have to touch Lol's SHE (or we haven't done our job!).

FWIW `HomomRLWR.hs` currently uses Lol's `mulPublic` (no underscore)
https://github.com/cpeikert/ALCHEMY/blob/8027787d9733b2693e5b887377cad435bbc216b1/examples/HomomRLWR.hs#L55-L57

mainly because it looks cleaner than `flip  (eval . mulPublic_)`

**Comment by cpeikert** [comment]
Yeah, but we know this is a hack that somehow comes from us not quite doing our intended job :) -- we're mixing two Haskell functions that come from the evaluator applied to different DSL programs.

**Pull request merged**
