### PR TITLE
Expand Kleislify to match Cyc2CT

### PR DESCRIPTION
**Pull request by crossroads1112**
Both Kleislify and Cyc2CT are shown and the paper. Cyc2CT has instances for lists and pairs, but Kleislify does not and there is no clear reason why. This PR adds these instances and also provides a `Pair`, `List` and `String` instance for `ErrorRateWriter` since it is now possible to write these.

### CODE REVIEW

**Comment by cpeikert** [comment]
Something about this doesn't quite make sense to me. Take lists for example. Why should `Kleislify w [a] = [Kleislify w a]`?  If my original object-language expression has type `[Ciphertext]`, then do I really want the new expression to have type `[w Ciphertext] ~= [(Ciphertext, ErrorLog)]`? Don't I instead want `w [Ciphertext] ~= ([Ciphertext], ErrorLog)`, where the second part logs the error rates of all the ciphertexts in the list?

I can get the latter from the former using `sequence`, right? Perhaps I'm suggesting that `Kleislify` not have those new definitions, but instead the interpretation of `List` should involve `sequence`ing.

**Comment by crossroads1112** [comment]
`Kleislify w Ciphertext ~ Ciphertext` not `w Ciphertext`

The current version I think makes sense. For example
```
Kleislify w (CT -> [CT]) ~ Kleislify w CT -> w (Kleislify w [CT]) 
                         ~ CT -> w [Kleislify w CT] 
                         ~ CT -> w [CT] 
                         ~ CT -> ([CT], ErrorLog)
```
This is exactly what we would expect, no?

**Comment by cpeikert** [comment]
Aha, you're right that I was sticking an extra `w` in there. But then why do we need the new cases for lists (and pairs) at all? In case it's a list of functions, I suppose?

I now agree that this makes the types work out as we want, but it seems pretty ad-hoc to be adding new cases all over. What is the principle behind this?

**Comment by crossroads1112** [comment]
List of functions are the difference, yes. 

Principle-wise: I've been trying to come up with a nice category-theoretical reason for this but it has proven rather confusing since e.g. `a -> b` represents a morphism between types `a` and `b`, but is itself a type.

I think the intuition though is that with Kleislify we are saying that in the context of ERW `->` simply means something else in the object language than it does in the metalanguage (suppose we represent it like so `(a ->: b) ~ (a -> w b)`). Essentially what Kleislify is doing is finding all instances of `->` and replacing it with `->:`. In order to do this it needs to be able to "look inside" pairs and lists otherwise we could be left with some strange combination of `->:` and `->` in the resulting types.

**Comment by crossroads1112** [comment]
In fact, I think there is an equivalent "bottum-up" version of this that makes this delineation more clear (we've looked at something like this in the past):

```
class Lambda expr where
    type Arrow expr :: * -> * -> *
    type Arrow expr = (->)
    lamDB :: expr (e,a) b -> expr (Arrow expr a b)
    ($:) :: expr e (Arrow expr a b) -> expr e a -> expr e b
    ...

instance Lambda E where
    -- Doesn't change

instance (Arrow expr ~ (->), ...)  -- Not sure if this constraint is necessary
=> Lambda (ErrorRateWriter expr z k w) where
    type Arrow (ErrorRateWriter expr z k w) = Kleisli w
```

**Comment by cpeikert** [comment]
OK, I'm convinced by the argument that we just want to find all occurrence of `->`.

The bottom-up approach does seem like the proper way to go, in that it doesn't require recursing into all the various types that could contain a function. For example, the top-down approach runs into problems if the exposed object-language type contains a monad, like `m (b -> c)` -- especially because `a -> b -> c` is an instance of `m (b -> c)`, with `m ~ (->) a`...

How much work would it be to try to the bottom-up `Arrow` approach for `Lambda_`?  Almost none of the instances have to change, right?  (Assuming the `Arrow` associated type can actually be defined to have a default.)

**Comment by crossroads1112** [comment]
> Assuming the Arrow associated type can actually be defined to have a default.

It can.

>  Almost none of the instances have to change, right?

None of the instances change, but the signature for every DSL function does, and not in a very positive way.

Consider
 `liftA2_ :: _ => expr e ((a -> b -> c) -> m a -> m b -> m c`
This becomes
`liftA2_ :: _ => expr e (Arrow expr (Arrow expr a (Arrow expr b c)) (Arrow expr (m a) (Arrow expr (m b) (m c)))`
which is basically unreadable. 

Ideally we'd have a type operator, something like this:

`type a ->: b`

Unfortunately using this as an associated type constructor still doesn't work because we have to specify give it `expr` as as parameter and `(->:) expr a b` is really no more readable.

Another alternative is to make Lambda a multiparameter type class with a fundep:

```
class Lambda expr arr | expr -> arr where
  lam :: expr (e, a) b -> expr (a `arr` b)
  app :: expr e (a `arr` b) -> expr e a -> expr e b
``` 

which initially looks promising. Frustratingly however,  types as infix operators by default associate _left_ which is the opposite of we want. Even more frustratingly, there does not seem to be a way to change this. With normal type operators `infixr` works but it does not appear to work for this "ad-hoc" type operator we've introduced here. 

I agree that the bottom-up approach is better, but I don't see a way to make it syntactically viable.

**Comment by cpeikert** [comment]
>
> None of the instances change, but the signature for every DSL function
> does, and not in a very positive way.
>

Ahh, right, this is what killed the idea before.


> Another alternative is to make Lambda a multiparameter type class with a
> fundep:
>
> class Lambda expr arr | expr -> arr where
>   lam :: expr (e, a) b -> expr (a `arr` b)
>   app :: expr e (a `arr` b) -> expr e a -> expr e b
>
> which initially looks promising. Frustratingly however, types as infix
> operators by default associate *left* which is the opposite of we want.
> Even more frustratingly, there does not seem to be a way to change this.
> With normal type operators infixr works but it does not appear to work
> for this "ad-hoc" type operator we've introduced here.
>
So close! We probably would've gotten bit somewhere down the line with a
weakness of fundeps anyway.

Just to be sure: there's no way to replace the `arr` argument with an
actual operator like `(:->)` and then use `infixr` to globally make it
right-associative, is there?

**Comment by crossroads1112** [comment]
> Just to be sure: there's no way to replace the `arr` argument with an actual operator like `(:->)` and then use `infixr` to globally make it right-associative, is there?

I tried just about every permutation of this I could think of. No luck.

**Pull request merged**
